application: hacktehfuture
version: 5
runtime: python
api_version: 1

default_expiration: "1d"

handlers:
  - url: /wiki
    script: wiki.py

  - url: /favicon.ico
    static_files: static/images/favicon.ico
    upload: static/images/favicon.ico

  - url: /static/images/fileicons/.*
    script: zip_handler.py

  - url: /fckeditor/.*
    script: zip_handler.py

  - url: /projects/chess
    static_files: static/projects/chess/chess.html
    upload: static/projects/chess/chess.html

  - url: /projects/chess_editor
    static_files: static/projects/chess/chess_editor.html
    upload: static/projects/chess/chess_editor.html

  - url: /projects/pong
    static_files: static/projects/pong/pong.html
    upload: static/projects/pong/pong.html

  - url: /projects/pong_editor
    static_files: static/projects/pong/pong_editor.html
    upload: static/projects/pong/pong_editor.html

  - url: /projects/html
    static_files: static/html/index.html
    upload: static/html/index.html

  - url: /projects
    static_files: static/projects/projectlist.html
    upload: static/projects/projectlist.html

  - url: /static
    static_dir: static

  - url: /admin/.*
    script: main.py
    login: required

  - url: /
    static_files: static_pretty/index.html
    upload: static_pretty/index.html

  - url: /
    static_dir: static_pretty

skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 (dev/.*)|
 (tests/.*)|
 (docs/.*)|
 )$
